import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { CalendarIcon } from "@heroicons/react/24/solid";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <header 
        className="bg-black text-white py-4 shadow-lg" 
        style={{
          backgroundColor: 'black',
          color: 'white',
          padding: '1rem',
          fontFamily: 'Helvetica Neue, Arial, sans-serif',
          }}>
          <div 
          className="container mx-auto flex justify-center">
            <h1 
            className="text-xl md:text-3xl font-bold">
              <span><CalendarIcon className="h-6 w-6 text-green-500 mr-2" /></span>
              <span className="text-blue-500">My</span>{" "}
              <span className="text-green-500">Todo's</span>
            </h1>
          </div>
        </header>
        <div>{children}</div>
      </body>
    </html>
  );
}
